In [1]:
a=10
b=3.124
c=10+5j
print(a)

10


In [2]:
print(int(b),float(a),str(c))

3 10.0 (10+5j)


In [3]:
s=lambda x: x*x
print(s(4))

16


In [4]:
s1=lambda x,y:x+y
print(s1(2,3))

5


In [5]:
# s=map(list(int,input().split())) 

In [6]:
mylist=[1,2.3,"hello"]
mylist

[1, 2.3, 'hello']

In [7]:
mytuple=(1,2.3,"hello")
mytuple

(1, 2.3, 'hello')

In [8]:
mydict={
    "name":"khwaab",
    "age": 22,
    "email":"Khwaabthareja23@gmail.com"
}
mydict

{'name': 'khwaab', 'age': 22, 'email': 'Khwaabthareja23@gmail.com'}

In [9]:
s=set([1,2,2,3,4,4,5])
s

{1, 2, 3, 4, 5}

In [10]:
s1={1,2,3,4,5,5,5,6,7,7}
s1

{1, 2, 3, 4, 5, 6, 7}

In [2]:
w=input().split()
print(w)

hello world
['hello', 'world']


In [3]:
i=list(map(int,input().split()))

1 2 3 4 5


In [4]:
print(i)

[1, 2, 3, 4, 5]


In [6]:
b=["a","b","c"]
a="".join(b)
print(a)

abc


In [8]:
l1=map(lambda x:x*2,[10,20,30,40])
for i in l1:
    print(i)

20
40
60
80


In [10]:
s1=filter(lambda x:x%2==0,[1,2,4,20,21,23])
for i in s1:
    print(i)

2
4
20


In [11]:
s1

In [12]:
l=[1,2,3,4,5,6,7]

In [13]:
l.append(8)
l

[1, 2, 3, 4, 5, 6, 7, 8]

In [14]:
l.clear()

In [15]:
l

[]

In [16]:
for i in range(8):
    l.append(i)

In [17]:
l

[0, 1, 2, 3, 4, 5, 6, 7]

In [18]:
s=l.copy()

In [19]:
s

[0, 1, 2, 3, 4, 5, 6, 7]

In [20]:
s is l

False

In [21]:
y=l
y

[0, 1, 2, 3, 4, 5, 6, 7]

In [22]:
y.append(9)

In [23]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 9]

In [24]:
l1=[10,11,12,13]
l1.extend(l)
l1

[10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 9]

In [25]:
l1.sort()

In [26]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13]

In [27]:
x=15
y=5
x//y

3

In [33]:
x=5
x*=3
x

15

In [30]:
x=5
y=3
x==y

False

In [31]:
x=[1,2]
y=[1,2]
x is y

False

In [32]:
z=x
z is x

True

In [34]:
l2=[1,2,3,4,5,6]
6 in l2

True

In [35]:
7 in l2

False

In [36]:
7 not in l2

True

In [37]:
l1.index(10)

9

In [38]:
l1.insert(0,"khwaab")
l1

['khwaab', 0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13]

In [39]:
l1.pop

<function list.pop(index=-1, /)>

In [40]:
l1

['khwaab', 0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13]

In [41]:
l1.pop()

13

In [42]:
l1

['khwaab', 0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12]

In [43]:
l1.pop(0)

'khwaab'

In [45]:
l1.append(8)
l1.sort()
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 10, 11, 12]

In [46]:
 l1.remove(0)

In [47]:
l1

[1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 10, 11, 12]

In [48]:
l1.reverse()
l1

[12, 11, 10, 9, 8, 8, 7, 6, 5, 4, 3, 2, 1]

In [49]:
l1.sort()

In [50]:
l1

[1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 10, 11, 12]

In [51]:
for i in "khwaab":
    print(i)

k
h
w
a
a
b


In [52]:
print(input()[::-1])

khwaab
baawhk


In [55]:
def myname(fname):
    return "My name is "+ fname
print(myname("khwaab"))

My name is khwaab


In [57]:
import sys
print("python version")
print(sys.version)

python version
3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]


In [58]:
from datetime import date
today=date.today()
print(today)

2022-02-07


In [60]:
import datetime
now=datetime.datetime.now()
print(now)

2022-02-07 14:42:44.829858


In [63]:
f=open("newfile10.txt","w")
f.write("hello i am khwaab")
f.close()

In [64]:
with open("newfile10.txt","w") as f:
    f.write("hi i am back")
    f.close()

In [65]:
with open("newfile10.txt","a") as f:
    f.write("hi i am back again")
    f.close()

In [2]:
import numpy as np
l=[12,3,4,5,6,7]
arr=np.array(l)
print(arr)

[12  3  4  5  6  7]


In [3]:
arr=np.arange(0,11,2)
print(arr)

[ 0  2  4  6  8 10]


In [4]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
compute=lambda x,y,z:x+y+z
x=int(input())
print(compute(x,10*x+x,100*x+10*x+x))

2
246


In [8]:
colors=["white","black","red","blue","green","purple"]
print(colors[0],colors[-1])

white purple


In [23]:
from datetime import date,timedelta
t = date.today()+timedelta(1)
print("exam date:", t)

exam is on: 2022-02-08


In [2]:
filename=input()
x=filename.split(".")
print(x[1])

hello.txt
txt


In [ ]:
print(input().split(".")[-1])

In [ ]:
# array zeros ones eye

In [3]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
print(np.zeros((2,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
class dog:
    a="khwaab"
    b="bye"
    def intro(self):
        print("hi",self.a)

Tommy=dog()
Tommy.intro()
print(Tommy.b)



hi khwaab
bye


In [9]:
abs(1+1j)

1.4142135623730951

In [10]:
k=[0,False]
print(all(k))

False


In [11]:
k=[]
print(all(k))

True


In [12]:
x=10
y=bin(x)
print(y)

0b1010


In [13]:
x=9
exec("print(x==9)")
exec("print(x<3)")

True
False


In [14]:
l=[1,2,3,4]
print(all(l))

True


In [15]:
l1=[False,1]
print(any(l1))

True


In [18]:
#format function

print(format(28,"d"))
print(format(28,"b"))
print(format(28.55,"f"))

28
11100
28.550000


In [19]:
import numpy as np
x=[[1,2],[3,4]]
y=np.linalg.inv(x)
answer=np.dot(x,y)
print(answer)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [2]:
#1
list1=list(map(int,input("Enter the numbers for the list: ").split()))
print("Ans1. Max number from the list is: ",max(list1))
print()

#2
list2=list(map(int,input("Enter the numbers you want the sum for:  ").split()))
print("Ans2. Sum of the numers is: ", sum(list2))
print()


#3
mul=1
list3=list(map(int,input("Enter the numbers you want the product for:  ").split()))
for i in list3:
    mul*=i
print("Ans3. Multiplication of all numbers is ",mul)
print()


#4
str1=input("enter the string: ")
print("Ans4. The reverse of string",str1,"is:",str1[::-1])
print()

#5
print("Ans 5.")
def factorial(n):
    if n==1 or n==0:
        return 1
    else:
        return n*factorial(n-1)
n=int(input("Enter the number you want the factorial of: "))
print("Ans5. The factoril of the given number is ", factorial(n))
print()

#6
print("Ans 6.")
def checkRange(n,low,high):
    
    if n>low and n<high:
        print("The given number is with the range")
    else:
        print("The given number is out of range")
        
        
low=int(input("Enter the lower number: "))
high=int(input("Enter the higher number: "))
n=int(input("Enter the number you want to check: "))
checkRange(n,low,high)
print()

#7
print("Ans 7.")
even=filter(lambda x: x%2==0,list(map(int,input("Enter the numbers for the list: ").split())))
print("Even numbers from the given list is: ",end=" ")
for i in even:
    print(i,end=" ")

Enter the numbers for the list: 1 2 3 4 5 6
Ans1. Max number from the list is:  6

Enter the numbers you want the sum for:  1 2 3 4 5
Ans2. Sum of the numers is:  15

Enter the numbers you want the product for:  1 2 3 4 5
Ans3. Multiplication of all numbers is  120

enter the string: khwaab thareja
Ans4. The reverse of string khwaab thareja is: ajeraht baawhk

Ans 5.
Enter the number you want the factorial of: 6
Ans5. The factoril of the given number is  720

Ans 6.
Enter the lower number: 2
Enter the higher number: 15
Enter the number you want to check: 13
The given number is with the range

Ans 7.
Enter the numbers for the list: 1 2 3 4 5 6 7 8
Even numbers from the given list is:  2 4 6 8 